/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * This file is normally generated by `npx convex dev`.
 * It is checked in here so the app can type-check before a Convex deployment is configured.
 */

import type { ApiFromModules, FilterApi, FunctionReference } from "convex/server";
import { anyApi } from "convex/server";
import type * as labsEvidence from "../labsEvidence.js";
import type * as nftMintRecords from "../nftMintRecords.js";
import type * as workItems from "../workItems.js";

const fullApi: ApiFromModules<{
  labsEvidence: typeof labsEvidence;
  nftMintRecords: typeof nftMintRecords;
  workItems: typeof workItems;
}> = anyApi as any;

export const api: FilterApi<typeof fullApi, FunctionReference<any, "public">> =
  anyApi as any;

export const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
> = anyApi as any;
